version: '2' #versi pertama, NGINX, php:latest, mysql, phpmyadmin, feel free untuk tambahkan apache -> naikan ke versi +1 (ex 2) kalau menambahlkan container baru, sub version (ex 1.1) untuk edit container yang ada

volumes:
    database_data:
        driver: local

services:
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./www:/www
        volumes_from:
            - php
    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - ./www:/www
    mysql:
        image: mysql:latest
        expose:
            - 3306
        volumes:
            - database_data:/var/lib/mysql
            - ./dump/mvc-starter.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: mvc
            MYSQL_USER: root
            MYSQL_PASSWORD: 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports: 
            - 8090:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306